// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddCategoryModal: typeof import('./src/components/organisms/AddCategoryModal.vue')['default']
    AddFolderModal: typeof import('./src/components/organisms/AddFolderModal.vue')['default']
    AddImageModal: typeof import('./src/components/organisms/AddImageModal.vue')['default']
    Alert: typeof import('./src/components/atoms/Alert.vue')['default']
    BottomNav: typeof import('./src/components/organisms/BottomNav.vue')['default']
    Button: typeof import('./src/components/atoms/Button.vue')['default']
    Folder: typeof import('./src/components/molecules/Folder.vue')['default']
    Home: typeof import('./src/pages/home.vue')['default']
    Img: typeof import('./src/components/atoms/Img.vue')['default']
    ImgModal: typeof import('./src/components/molecules/ImgModal.vue')['default']
    Input: typeof import('./src/components/atoms/Input.vue')['default']
    Modal: typeof import('./src/components/atoms/Modal.vue')['default']
    PhotoKeepTitle: typeof import('./src/components/atoms/PhotoKeepTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortcutAction: typeof import('./src/components/organisms/ShortcutAction.vue')['default']
    SlideContent: typeof import('./src/components/molecules/SlideContent.vue')['default']
    Undefined: typeof import('./src/pages/index.vue')['default']
    Uploader: typeof import('./src/components/atoms/Uploader.vue')['default']
  }
}

export {}
