Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Auth.User
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
