service: aws-photokeep-dynamodb

package:
  exclude:
    - node_modules/aws-sdk/**

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  stage: api
  lambdaHashingVersion: 20201221

custom:
  dynamodb:
    start:
      port: 8000
      migrate: true
      seed: true
      convertEmptyValues: true
    stages:
      - api
    seed:
      domain:
        sources:
          - table: Auth.User
            sources: [./data/Auth.User.json]

  serverless-offline:
    port: 3999

plugins:
  - serverless-dynamodb-local
  - serverless-offline

resources:
  - ${file(./db.yml)}
