// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddCategoryModal: typeof import('./components/organisms/AddCategoryModal.vue')['default']
    AddFolderModal: typeof import('./components/organisms/AddFolderModal.vue')['default']
    AddImageModal: typeof import('./components/organisms/AddImageModal.vue')['default']
    Alert: typeof import('./components/atoms/Alert.vue')['default']
    BottomNav: typeof import('./components/organisms/BottomNav.vue')['default']
    Button: typeof import('./components/atoms/Button.vue')['default']
    Folder: typeof import('./components/molecules/Folder.vue')['default']
    Icon: typeof import('./components/atoms/Icon.vue')['default']
    Img: typeof import('./components/atoms/Img.vue')['default']
    ImgModal: typeof import('./components/molecules/ImgModal.vue')['default']
    Input: typeof import('./components/atoms/Input.vue')['default']
    KBtn: typeof import('./components/atoms/KBtn.vue')['default']
    KeepimTitle: typeof import('./components/atoms/KeepimTitle.vue')['default']
    KInput: typeof import('./components/atoms/KInput.vue')['default']
    Modal: typeof import('./components/atoms/Modal.vue')['default']
    PhotoKeepTitle: typeof import('./components/atoms/PhotoKeepTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortcutAction: typeof import('./components/organisms/ShortcutAction.vue')['default']
    SlideContent: typeof import('./components/molecules/SlideContent.vue')['default']
    Uploader: typeof import('./components/atoms/Uploader.vue')['default']
  }
}
