service: photo-keep

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1

functions:
  test:
    handler: src/routes/test/test.handler
    memorySize: 128
    events:
      - http:
          path: /
          method: GET

  authLogin:
    handler: src/routes/auth/login.handler
    memorySize: 128
    events:
      - http:
          path: /auth
          method: POST

  registerUser:
    handler: src/routes/user/post.handler
    memorySize: 128
    events:
      - http:
          path: /register
          method: POST

  validateToken:
    handler: src/routes/auth/token.handler
    memorySize: 128
    events:
      - http:
          path: /validate-token
          method: POST

  createFolder:
    handler:
      - src/middleware/authorization.handler
      - then: src/routes/folder/post.handler
      - catch: src/utils/handlerError.handler
    memorySize: 128
    events:
      - http:
          path: /folder
          method: POST

  getFolder:
    handler:
      - src/middleware/authorization.handler
      - then: src/routes/folder/get.handler
      - catch: src/utils/handlerError.handler
    memorySize: 128
    events:
      - http:
          path: /folder
          method: GET

custom:
  serverless-offline:
    httpPort: 4000
    websocketPort: 4001
    lambdaPort: 4002

  prune:
    automatic: true
    number: 3

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations

plugins:
  - serverless-middleware
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin
  - serverless-dotenv-plugin
