service: keepim-api

frameworkVersion: "3"

plugins:
  - serverless-esbuild
  - serverless-iam-roles-per-function
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"

functions:
  Health:
    handler: src/functions/health/handler.main
    events:
      - http:
          method: get
          path: health
  GetUser:
    handler: src/functions/user/get-user/handler.main
    events:
      - http:
          method: get
          path: user/{id}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:sa-east-1:531760387770:table/Keepim.User

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node18
    define:
      "require.resolve": undefined
    platform: node
    concurrency: 10

  prune:
    automatic: true
    number: 3

  serverlessOffline:
    httpPort: 4000
    websocketPort: 4001
    lambdaPort: 4002

  dynamodb:
    stages: dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: Keepim.User
            sources:
              - ./migration/user-seed.json

resources: ${file(./db-resources.yml)}
