service: photo-keep

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1

functions:
  authLogin:
    handler: src/routes/auth/post.run
    memorySize: 128
    events:
      - http:
          path: /auth
          method: POST

custom:
  serverless-offline:
    httpPort: 4000

  prune:
    automatic: true
    number: 3

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin
