service: photo-keep

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1

functions:
  authLogin:
    handler: src/routes/auth/login.run
    memorySize: 128
    events:
      - http:
          path: /auth
          method: POST

  registerUser:
    handler: src/routes/user/post.run
    memorySize: 128
    events:
      - http:
          path: /register
          method: POST

  validateToken:
    handler: src/routes/auth/token.run
    memorySize: 128
    events:
      - http:
          path: /validate-token
          method: POST

custom:
  serverless-offline:
    httpPort: 4000
    websocketPort: 4001
    lambdaPort: 4002

  prune:
    automatic: true
    number: 3

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin
  - serverless-dotenv-plugin
