name: deploy

on:
  push:
    branches:
      - main

jobs:
  check_changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      api: ${{ steps.filter.outputs.api }}
      app: ${{ steps.filter.outputs.app }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          api:
            - 'api/**'
          app:
            - 'app/**'

  build_api:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.api == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: API Version Update
        id: api-version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          change_path: "./api"

      - name: Install dependencies
        run: npm install
        working-directory: ./api

      - name: Deploy API
        run: npx serverless deploy --stage production
        working-directory: ./api
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REFRESH_TOKEN_LENGTH: ${{ secrets.REFRESH_TOKEN_LENGTH }}
          JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
          REFRESH_TOKEN_EXPIRATION: ${{ secrets.REFRESH_TOKEN_EXPIRATION }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          COLLECTION_DB_TABLE: ${{ secrets.COLLECTION_DB_TABLE }}
          SESSION_DB_TABLE: ${{ secrets.SESSION_DB_TABLE }}
          USER_DB_TABLE: ${{ secrets.USER_DB_TABLE }}

  build_app:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.app == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      
      - name: API Version Update
        id: api-version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          change_path: "./app"

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Vite Build
        run: npm run build
        working-directory: ./app

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "sa-east-1"
          SOURCE_DIR: "app/dist"
  
  update_develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull main to develop
        run: |
          git checkout develop
          git pull origin main
