name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-api:
    if: ${{ contains(github.event.head_commit.modified, 'api/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install
        working-directory: ./api

      - name: Deploy API
        run: npx serverless deploy --stage production
        working-directory: ./api
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REFRESH_TOKEN_LENGTH: ${{ secrets.REFRESH_TOKEN_LENGTH }}
          JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
          REFRESH_TOKEN_EXPIRATION: ${{ secrets.REFRESH_TOKEN_EXPIRATION }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SESSION_DB_TABLE: ${{ secrets.SESSION_DB_TABLE }}
          USER_DB_TABLE: ${{ secrets.USER_DB_TABLE }}

  build:
    if: ${{ contains(github.event.head_commit.modified, 'app/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node version
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Setup Env
        run: npm install
        working-directory: ./app

      - name: Vite Build
        run: npm run build
        working-directory: ./app

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "sa-east-1"
          SOURCE_DIR: "app/dist"
